name: Reputation
main: com.gmail.derpwave.Reputation
version: 0.2


commands:
   getmaprep:
      description: get player reputation from the hashmap  
      usage: /getmaprep [player]
      permission: getmaprep.rn
      permission-message: You don't have permission to use this command.
      
      
   setmaprep:
      description: set player reputation in the hashmap  
      usage: /setmaprep [player] [value]
      permission: setmaprep.rn
      permission-message: You don't have permission to use this command.
      
   altmaprep:
      description: alter player reputation in the hashmap  
      usage: /altmaprep [player] [value]
      permission: altmaprep.rn
      permission-message: You don't have permission to use this command.
      
   savereps:
      description: save repmap to file  
      usage: /savereps
      permission: savereps.rn
      permission-message: You don't have permission to use this command.
      
   readreps:
      description: read repmap from file  
      usage: /readreps
      permission: readreps.rn
      permission-message: You don't have permission to use this command.